version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      github-actions:
        patterns: ["*"]
        update-types: [minor, patch]
  # Python uv
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      python-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  # bun
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    ignore:
      - dependency-name: "@hey-api/openapi-ts"
    groups:
      bun-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  # Flutter/Dart
  - package-ecosystem: pub
    directory: /mobile
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      pub-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  # Docker
  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      docker-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  # Docker Compose
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ⬆
    labels: [dependencies, internal]
    groups:
      docker-compose-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
