// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CompleteUploadRequestSchema = {
    properties: {
        folder_path: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Folder Path'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        mime_type: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Mime Type'
        },
        category: {
            '$ref': '#/components/schemas/FileCategory'
        },
        blob_hash: {
            type: 'string',
            maxLength: 64,
            minLength: 64,
            title: 'Blob Hash'
        },
        size_bytes: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Size Bytes'
        }
    },
    type: 'object',
    required: ['folder_path', 'name', 'mime_type', 'category', 'blob_hash', 'size_bytes'],
    title: 'CompleteUploadRequest'
} as const;

export const FileCategorySchema = {
    type: 'string',
    enum: ['image', 'video', 'audio', 'document', 'spreadsheet', 'archive', 'other'],
    title: 'FileCategory'
} as const;

export const FileShareCreateSchema = {
    properties: {
        recipient_email: {
            type: 'string',
            format: 'email',
            title: 'Recipient Email'
        }
    },
    type: 'object',
    required: ['recipient_email'],
    title: 'FileShareCreate'
} as const;

export const FileSharePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        file_id: {
            type: 'string',
            format: 'uuid',
            title: 'File Id'
        },
        recipient_email: {
            type: 'string',
            format: 'email',
            title: 'Recipient Email'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'file_id', 'recipient_email', 'created_at'],
    title: 'FileSharePublic'
} as const;

export const FileSharesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FileSharePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FileSharesPublic'
} as const;

export const FolderContentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category'
        },
        blob_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blob Hash'
        },
        size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Size Bytes'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        owner_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Email'
        }
    },
    type: 'object',
    required: ['id', 'name', 'type'],
    title: 'FolderContentPublic'
} as const;

export const FolderCreateSchema = {
    properties: {
        parent_path: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Parent Path'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['parent_path', 'name'],
    title: 'FolderCreate'
} as const;

export const FolderPublicSchema = {
    properties: {
        path: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Path'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['path', 'name', 'id', 'owner_id'],
    title: 'FolderPublic'
} as const;

export const FolderWithContentsPublicSchema = {
    properties: {
        path: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Path'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        contents: {
            items: {
                '$ref': '#/components/schemas/FolderContentPublic'
            },
            type: 'array',
            title: 'Contents'
        }
    },
    type: 'object',
    required: ['path', 'name', 'id', 'owner_id', 'contents'],
    title: 'FolderWithContentsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event_type: {
            type: 'string',
            title: 'Event Type'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        }
    },
    type: 'object',
    required: ['id', 'event_type', 'payload', 'created_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'NotificationsPublic'
} as const;

export const PresignDownloadResponseSchema = {
    properties: {
        download_url: {
            type: 'string',
            title: 'Download Url'
        },
        method: {
            type: 'string',
            title: 'Method',
            default: 'GET'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['download_url', 'expires_in'],
    title: 'PresignDownloadResponse'
} as const;

export const PresignUploadRequestSchema = {
    properties: {
        folder_path: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Folder Path'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        mime_type: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Mime Type'
        },
        category: {
            '$ref': '#/components/schemas/FileCategory'
        },
        blob_hash: {
            type: 'string',
            maxLength: 64,
            minLength: 64,
            title: 'Blob Hash'
        },
        size_bytes: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Size Bytes'
        }
    },
    type: 'object',
    required: ['folder_path', 'name', 'mime_type', 'category', 'blob_hash', 'size_bytes'],
    title: 'PresignUploadRequest'
} as const;

export const PresignUploadResponseSchema = {
    properties: {
        upload_required: {
            type: 'boolean',
            title: 'Upload Required',
            default: true
        },
        upload_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Upload Url'
        },
        method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Method',
            default: 'PUT'
        },
        headers: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Headers'
        },
        object_key: {
            type: 'string',
            title: 'Object Key'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['headers', 'object_key', 'expires_in'],
    title: 'PresignUploadResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SharedFilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        category: {
            type: 'string',
            title: 'Category'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        owner_email: {
            type: 'string',
            format: 'email',
            title: 'Owner Email'
        },
        shared_at: {
            type: 'string',
            format: 'date-time',
            title: 'Shared At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'mime_type', 'category', 'size_bytes', 'owner_email', 'shared_at'],
    title: 'SharedFilePublic'
} as const;

export const SharedFilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SharedFilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SharedFilesPublic'
} as const;

export const StoredFilePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        mime_type: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Mime Type'
        },
        category: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Category'
        },
        blob_hash: {
            type: 'string',
            maxLength: 128,
            minLength: 1,
            title: 'Blob Hash'
        },
        size_bytes: {
            type: 'integer',
            minimum: 0,
            title: 'Size Bytes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        folder_id: {
            type: 'string',
            format: 'uuid',
            title: 'Folder Id'
        }
    },
    type: 'object',
    required: ['name', 'mime_type', 'category', 'blob_hash', 'size_bytes', 'id', 'owner_id', 'folder_id'],
    title: 'StoredFilePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnreadCountPublicSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['count'],
    title: 'UnreadCountPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;