// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CompleteUploadRequest = {
    folder_path: string;
    name: string;
    mime_type: string;
    category: FileCategory;
    blob_hash: string;
    size_bytes: number;
};

export type FileCategory = 'image' | 'video' | 'audio' | 'document' | 'spreadsheet' | 'archive' | 'other';

export type FileShareCreate = {
    recipient_email: string;
};

export type FileSharePublic = {
    id: string;
    file_id: string;
    recipient_email: string;
    created_at: string;
};

export type FileSharesPublic = {
    data: Array<FileSharePublic>;
    count: number;
};

export type FolderContentPublic = {
    id: string;
    name: string;
    type: string;
    path?: (string | null);
    mime_type?: (string | null);
    category?: (string | null);
    blob_hash?: (string | null);
    size_bytes?: (number | null);
};

export type FolderCreate = {
    parent_path: string;
    name: string;
};

export type FolderPublic = {
    path: string;
    name: string;
    id: string;
    owner_id: string;
    parent_id?: (string | null);
};

export type FolderWithContentsPublic = {
    path: string;
    name: string;
    id: string;
    owner_id: string;
    parent_id?: (string | null);
    contents: Array<FolderContentPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PresignDownloadResponse = {
    download_url: string;
    method?: string;
    expires_in: number;
};

export type PresignUploadRequest = {
    folder_path: string;
    name: string;
    mime_type: string;
    category: FileCategory;
    blob_hash: string;
    size_bytes: number;
};

export type PresignUploadResponse = {
    upload_url: string;
    method?: string;
    headers: {
        [key: string]: (string);
    };
    object_key: string;
    expires_in: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SharedFilePublic = {
    id: string;
    name: string;
    mime_type: string;
    category: string;
    size_bytes: number;
    owner_email: string;
    shared_at: string;
};

export type SharedFilesPublic = {
    data: Array<SharedFilePublic>;
    count: number;
};

export type StoredFilePublic = {
    name: string;
    mime_type: string;
    category: string;
    blob_hash: string;
    size_bytes: number;
    id: string;
    owner_id: string;
    folder_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type FilesReadFilesSharedWithMeResponse = (SharedFilesPublic);

export type FilesCreateChildFolderData = {
    requestBody: FolderCreate;
};

export type FilesCreateChildFolderResponse = (FolderPublic);

export type FilesReadFilesData = {
    path?: string;
};

export type FilesReadFilesResponse = (FolderWithContentsPublic);

export type FilesPresignDownloadData = {
    fileId: string;
};

export type FilesPresignDownloadResponse = (PresignDownloadResponse);

export type FilesCreateFileShareData = {
    fileId: string;
    requestBody: FileShareCreate;
};

export type FilesCreateFileShareResponse = (FileSharePublic);

export type FilesReadFileSharesData = {
    fileId: string;
};

export type FilesReadFileSharesResponse = (FileSharesPublic);

export type FilesDeleteFileShareData = {
    fileId: string;
    shareId: string;
};

export type FilesDeleteFileShareResponse = (void);

export type FilesCompleteFileUploadData = {
    requestBody: CompleteUploadRequest;
};

export type FilesCompleteFileUploadResponse = (StoredFilePublic);

export type FilesPresignUploadData = {
    requestBody: PresignUploadRequest;
};

export type FilesPresignUploadResponse = (PresignUploadResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);