// This file is auto-generated by @hey-api/openapi-ts

export const FileCategorySchema = {
    type: 'string',
    enum: ['image', 'video', 'audio', 'document', 'spreadsheet', 'archive', 'other'],
    title: 'FileCategory'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        index: {
            type: 'string',
            title: 'Index'
        },
        engine: {
            type: 'string',
            title: 'Engine'
        }
    },
    type: 'object',
    required: ['status', 'index', 'engine'],
    title: 'HealthResponse'
} as const;

export const SearchResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/SearchResultItem'
            },
            type: 'array',
            title: 'Results'
        },
        next_cursor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Cursor'
        }
    },
    type: 'object',
    title: 'SearchResponse'
} as const;

export const SearchResultItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        folder_path: {
            type: 'string',
            title: 'Folder Path'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type'
        },
        category: {
            '$ref': '#/components/schemas/FileCategory'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'folder_path', 'mime_type', 'category', 'size_bytes', 'created_at'],
    title: 'SearchResultItem'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;