// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { SearchFilesApiV1SearchFilesGetData, SearchFilesApiV1SearchFilesGetResponse, HealthCheckApiV1SearchHealthGetResponse } from './types.gen';

export class SearchService {
    /**
     * Search Files
     * @param data The data for the request.
     * @param data.folderPath
     * @param data.q
     * @param data.category
     * @param data.limit
     * @param data.cursor
     * @returns SearchResponse Successful Response
     * @throws ApiError
     */
    public static filesApiV1SearchFilesGet(data: SearchFilesApiV1SearchFilesGetData): CancelablePromise<SearchFilesApiV1SearchFilesGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/search/files',
            query: {
                folder_path: data.folderPath,
                q: data.q,
                category: data.category,
                limit: data.limit,
                cursor: data.cursor
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Health Check
     * @returns HealthResponse Successful Response
     * @throws ApiError
     */
    public static healthCheckApiV1SearchHealthGet(): CancelablePromise<HealthCheckApiV1SearchHealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/search/health'
        });
    }
}